### ISSUE TITLE
about beamsearch

### ISSUE THREAD

**Issue by li512871889** [bladewaltz1/ModeCap#2]
Dear Author，I am confused that how to use beam search in your model ,Can you help me? Thank you!

**Comment by bladewaltz1** [comment]
Hi, thanks for you interest. We did not use beam search for our models. We only use it for the baseline models (Transformer and AoANet), where we follow the usage in their original codebase, e.g., setting the`beam_size` value in the config files.

**Comment by li512871889** [comment]
Thank you for your reply，It's a amazing work！

**Comment by bladewaltz1** [comment]
> Thank you for your reply，It's a amazing work！

thanks
